[WIP] GORM adapter
avito-tech/go-transaction-manager pull request #26
Opened 2022-11-06 09:14 UTC by maranqz

2022-11-13 14:55 UTC, maranqz commented
@Flaiers if you have time, you can check PR.

2022-11-14 04:06 UTC, Flaiers requested changes
why this files change in current pull request?

- mongo/example_test.go
- mongo/transaction_test.go
- sql/example_test.go
- sql/transaction_test.go
- sqlx/example_test.go
- sqlx/transaction_test.go

2022-11-18 16:38 UTC, maranqz commented on sqlx/transaction_test.go
> +					require.True(t, trNested.IsActive())
I simplified the code. I didn't moved it to another PR because it is small changes.
@Flaiers
https://github.com/avito-tech/go-transaction-manager/pull/26#pullrequestreview-1178422666

2022-11-21 17:17 UTC, Flaiers approved these changes

2022-11-22 15:51 UTC, merged